gc:
  onInterval: '* * * * *' # always trigger
  onLowSpace: 214748364800 # always trigger
  keepDays: 7 # how many days to keep old, unused stuff arround for rollbacks
  maxFree: 214748364800 # don't actually clean
system:
  gc: {} # override the gc from above
  upgrade: # affects nixos-rebuild
    interval: true # always trigger
    silentFetch: true # always trigger
    silentPrepare: true # always trigger
    forceSilentPrepare: true # always trigger
    silentApplyForNextBoot: true # build with nixos-rebuild boot so update gets applied on next boot
    notifyUpdateAvailable: true # make a notification to apply update during current boot
    rollback:
      checks:
        sanityCheck: true # perform checks while the system is running
        grubFlag: false # add settings to grub to auto-rollback
      allowAuto: critical # never, critical, always - change when auto-rollbacks are done
user:
  gc: {} # override the gc from above
  upgrade: # affects nix-env
    interval: true # always trigger
    silentFetch: true # always trigger
    silentPrepare: true # always trigger
    forceSilentPrepare: true # always trigger
cooldownMsAfterBoot: 1 # immediatly run stuff
